import sqlite3 from 'sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dbPath = path.resolve(__dirname, 'server', 'tours.db');
const db = new sqlite3.Database(dbPath);

const tours = [
  { title: "City Tour Cultural", shortDescription: "Recorrido guiado por los principales puntos de interés cultural e histórico de Cartagena.", fullDescription: "Recorrido guiado por los principales puntos de interés cultural e histórico de Cartagena. El tour incluye visitas a monumentos, plazas y sitios emblemáticos.", price: 0, duration: "4 horas", includes: JSON.stringify(["Guía turístico profesional y bilingüe", "Entrada al Castillo de San Felipe de Barajas", "Tour en chiva turística y cultural", "Recogida y retorno en el hotel"]), itinerary: JSON.stringify([]), category: "Cultural", images: JSON.stringify([]) },
  { title: "Night Party Boat", shortDescription: "Recorrido inolvidable por la bahía de Cartagena con música.", fullDescription: "Disfruta de un recorrido inolvidable por la bahía de Cartagena, con vistas espectaculares y una experiencia llena de música, entretenimiento y ambiente festivo a bordo.", price: 0, duration: "2 horas", includes: JSON.stringify(["Bote deportivo de lujo", "Full música y animación a bordo", "Barra libre", "Ingreso a discoteca Taboo"]), itinerary: JSON.stringify([]), category: "Fiesta", images: JSON.stringify([]) },
  { title: "Parque Tayrona Cabo San Juan", shortDescription: "Recorrido ecológico con caminata de dos horas hasta el Cabo San Juan.", fullDescription: "Recorrido ecológico con una caminata de aproximadamente dos horas hasta el Cabo San Juan. Durante el trayecto se observan siete playas.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre", "Entrada al Parque Nacional Tayrona", "Seguro médico", "Guía profesional"]), itinerary: JSON.stringify([]), category: "Naturaleza", images: JSON.stringify([]) },
  { title: "Playa Blanca Santa Marta", shortDescription: "Visita a Playa Blanca con transporte, almuerzo típico y entrada al acuario.", fullDescription: "Visita a Playa Blanca con transporte, almuerzo típico y entrada al acuario. Un recorrido que incluye guía profesional y seguro de viaje.", price: 0, duration: "Día completo", includes: JSON.stringify(["Almuerzo típico", "Transporte terrestre", "Entrada al acuario", "Seguro de viaje", "Guía turístico profesional"]), itinerary: JSON.stringify([]), category: "Playa", images: JSON.stringify([]) },
  { title: "Playas Tayrona Cinto y Playa Cristal", shortDescription: "Explora dos de las playas más hermosas del Parque Nacional Tayrona en un solo día.", fullDescription: "Explora dos de las playas más hermosas del Parque Nacional Tayrona en un solo día. Disfruta de medio día en Cinto y el otro en Playa Cristal.", price: 0, duration: "Día completo", includes: JSON.stringify(["Entradas al Parque Nacional Tayrona", "Transporte marítimo", "Seguro de asistencia", "Guía profesional"]), itinerary: JSON.stringify([]), category: "Playa", images: JSON.stringify([]) },
  { title: "Recorrido por Islas Top Luxury", shortDescription: "Exclusivo recorrido con paradas en cuatro hermosas islas privadas del Archipiélago de las Islas del Rosario.", fullDescription: "Disfruta de un exclusivo recorrido con paradas en cuatro hermosas islas privadas del Archipiélago de las Islas del Rosario. Un día de lujo, naturaleza y confort.", price: 0, duration: "Día completo", includes: JSON.stringify(["Paradas en Isla Vistamar, Sol y Papaya, Kokomo, Cocotera", "Recogida en hotel", "Transporte en bote deportivo", "Orientador bilingüe", "Snorkeling", "Almuerzo en Isla Kokomo"]), itinerary: JSON.stringify([]), category: "Lujo", images: JSON.stringify([]) },
  { title: "Playa Blanca Barú Playa Tranquila", shortDescription: "Transporte hacia Playa Blanca, uno de los destinos más visitados de Cartagena.", fullDescription: "Este tour incluye transporte hacia Playa Blanca, uno de los destinos más visitados de Cartagena. Durante el recorrido, los participantes podrán disfrutar de un almuerzo típico.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte desde el hotel", "Coctel de Bienvenida", "Cama solar o silla con mesa", "Almuerzo típico", "Guía profesional", "Seguro de viaje"]), itinerary: JSON.stringify([]), category: "Playa", images: JSON.stringify([]) },
  { title: "Tour 5 Islas Plancton", shortDescription: "Recorre algunos de los destinos más impresionantes del Caribe, finalizando con plancton bioluminiscente.", fullDescription: "Recorre algunos de los destinos más impresionantes del Caribe, con paradas en playas paradisíacas e islas llenas de vida marina, finalizando con la experiencia única del plancton bioluminiscente.", price: 0, duration: "Día completo", includes: JSON.stringify(["Desayuno", "Transporte climatizado", "Recorrido panorámico por Islas del Rosario", "Snorkel", "Almuerzo típico caribeño", "Actividad de plancton bioluminiscente"]), itinerary: JSON.stringify([]), category: "Aventura", images: JSON.stringify([]) },
  { title: "Tour Anaho Beach Club", shortDescription: "Disfruta de un día completo en un exclusivo complejo con transporte en lancha.", fullDescription: "Disfruta de un día completo en un exclusivo complejo con transporte en lancha, almuerzo a elección entre seis opciones, coctel de bienvenida y acceso a instalaciones como piscina, jacuzzi, playa.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte en lancha", "Coctel de bienvenida", "Almuerzo", "Uso de instalaciones (Piscina, Cama de playa, Jacuzzi, Playa, Baños)", "Wifi gratis"]), itinerary: JSON.stringify([]), category: "Lujo", images: JSON.stringify([]) },
  { title: "Tour Barranquilla VIP Shopping", shortDescription: "Descubre los íconos de Barranquilla en un tour único.", fullDescription: "Descubre los íconos de Barranquilla en un tour único: Sombrero Vueltiao, Ventana al Mundo, Malecón del Río y más. Disfruta un almuerzo a la carta y cierra el día con compras.", price: 0, duration: "Día completo", includes: JSON.stringify(["Sombrero Vueltiao", "Castillo de Salgar", "Letras de BARRANQUILLA", "Ventana al Mundo", "Malecón del Río", "Monumento Pies Descalzos", "Aleta del Tiburón", "Restaurante Carnavalero", "Museo del Carnaval", "Centro Comercial único"]), itinerary: JSON.stringify([]), category: "Cultural", images: JSON.stringify([]) },
  { title: "Buritaca Mar y Río", shortDescription: "Disfruta de un día lleno de naturaleza y tranquilidad en Buritaca.", fullDescription: "Disfruta de un día lleno de naturaleza y tranquilidad en Buritaca, un destino donde el río se encuentra con el mar. Perfecto para relajarte.", price: 0, duration: "8:00 AM - 4:00 PM", includes: JSON.stringify(["Almuerzo típico", "Transporte terrestre ida y vuelta", "Seguro de asistencia", "Guía profesional"]), itinerary: JSON.stringify([]), category: "Naturaleza", images: JSON.stringify([]) },
  { title: "Isla Múcura - Tintipán - Santa Cruz del Islote", shortDescription: "Recorrido por el Archipiélago de San Bernardo.", fullDescription: "Disfruta de un recorrido por el Archipiélago de San Bernardo, un paraíso caribeño con aguas turquesa, playas idílicas y experiencias únicas en contacto con la naturaleza.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre hasta Muelle La Bodeguita", "Transporte en lancha", "Guía turístico", "Seguro de viaje", "Snack", "Almuerzo típico"]), itinerary: JSON.stringify([{"time": "Parada 1", "activity": "Isla Tintipán"}, {"time": "Parada 2", "activity": "Casa en el Agua"}, {"time": "Parada 3", "activity": "Islote Santa Cruz"}, {"time": "Parada 4", "activity": "Isla Múcura"}]), category: "Aventura", images: JSON.stringify([]) },
  { title: "Pasdía Hotel Isla Palma", shortDescription: "Experiencia exclusiva en el Hotel Isla Palma, una reserva natural.", fullDescription: "Disfruta de una experiencia exclusiva en el Hotel Isla Palma, una reserva natural en el Archipiélago de San Bernardo. El recorrido incluye una parada en las Islas del Rosario.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre y en lancha", "Seguro de viaje y guía", "Snack", "Coctel", "Almuerzo Gourmet", "Acceso a playa", "Visita al BioParque"]), itinerary: JSON.stringify([]), category: "Lujo", images: JSON.stringify([]) },
  { title: "Tour Triple Minca, Taganga, Playa Grande", shortDescription: "Recorrido que integra ecoturismo y playa.", fullDescription: "Recorrido que integra ecoturismo y playa, con transporte, seguro de viaje y guía profesional. Incluye caminata ecológica en Minca, visita a Pozo Azul, parada en el mirador de Taganga y traslado a Playa Grande.", price: 0, duration: "Día completo", includes: JSON.stringify(["Desayuno típico", "Caminata ecológica a Pozo Azul", "Zona de baño", "Almuerzo típico", "Transporte terrestre hasta Taganga", "Transporte en lancha a Playa Grande", "Seguro y guía"]), itinerary: JSON.stringify([]), category: "Aventura", images: JSON.stringify([]) },
  { title: "Tour Palmarito Beach Club", shortDescription: "Transporte en lancha hacia el exclusivo Club Palmarito.", fullDescription: "Este tour incluye transporte en lancha hacia el exclusivo Club Palmarito, donde podrás disfrutar de un día de relajación en un entorno tranquilo y natural.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte en lancha", "Pasadía en el club", "Coctel de Bienvenida", "Almuerzo tipo buffet", "Cama solar o silla con mesa"]), itinerary: JSON.stringify([]), category: "Lujo", images: JSON.stringify([]) },
  { title: "Tour Palomino", shortDescription: "Día lleno de naturaleza, playa y tranquilidad en Palomino.", fullDescription: "Disfruta de un día lleno de naturaleza, playa y tranquilidad en Palomino, uno de los destinos más encantadores de la costa caribeña colombiana.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre", "Desayuno", "Almuerzo", "Guía profesional", "Seguro de vida"]), itinerary: JSON.stringify([]), category: "Naturaleza", images: JSON.stringify([]) },
  { title: "Punta Arena", shortDescription: "Día relajante en las playas de Punta Arena.", fullDescription: "Disfruta de un día relajante en las playas de Punta Arena, rodeado de tranquilidad y sabores típicos de la región.", price: 0, duration: "Día completo", includes: JSON.stringify(["Almuerzo", "Carpa de sol para tu comodidad"]), itinerary: JSON.stringify([]), category: "Playa", images: JSON.stringify([]) },
  { title: "Tour Santa Marta VIP", shortDescription: "Descubre lo mejor de Barranquilla y Santa Marta en un solo día.", fullDescription: "Descubre lo mejor de Barranquilla y Santa Marta en un solo día. Disfruta de playas paradisíacas, monumentos emblemáticos y sitios históricos.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte ida y vuelta", "Recorrido en Barranquilla", "Playa Blanca en Santa Marta", "City Tour en Santa Marta", "Desayuno", "Almuerzo típico", "Guía acompañante"]), itinerary: JSON.stringify([]), category: "Cultural", images: JSON.stringify([]) },
  { title: "Sierra Minca Adventure", shortDescription: "Experiencia inolvidable en la Sierra Nevada de Santa Marta.", fullDescription: "Vive una experiencia inolvidable en la Sierra Nevada de Santa Marta. Explora cascadas impresionantes, disfruta de vistas espectaculares y conéctate con la naturaleza.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte en vehículo 4x4", "Visita a las cascadas", "Bebida de bienvenida", "Acceso a Sierra Minca", "Almuerzo tipo gourmet", "Guía especializado", "Seguro de viaje"]), itinerary: JSON.stringify([]), category: "Aventura", images: JSON.stringify([]) },
  { title: "Tour Tayrona Playa Cristal", shortDescription: "Explora el Parque Nacional Tayrona con transporte terrestre climatizado.", fullDescription: "Explora el Parque Nacional Tayrona con transporte terrestre climatizado y entrada incluida. Visita el mirador de 7 olas y traslado en lancha hasta Playa Cristal.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre", "Entrada al Parque Nacional Tayrona", "Visita al mirador de 7 olas", "Transporte en lancha a Playa Cristal", "Guía profesional", "Seguro médico"]), itinerary: JSON.stringify([]), category: "Naturaleza", images: JSON.stringify([]) },
  { title: "Vista Al Mar Pasadía", shortDescription: "Día en el exclusivo beach club Vista Mar, ubicado en Isla Grande.", fullDescription: "Disfruta de un día en el exclusivo beach club Vista Mar, ubicado en Isla Grande, con aguas cristalinas y una vista impresionante.", price: 0, duration: "Día completo", includes: JSON.stringify(["Transporte terrestre climatizado", "Transporte en bote deportivo de lujo", "Coctel de bienvenida", "Uso de instalaciones", "Actividad deportiva (kayak)", "Almuerzo a la carta"]), itinerary: JSON.stringify([]), category: "Lujo", images: JSON.stringify([]) }
];

const stmt = db.prepare(`INSERT INTO tours (title, shortDescription, fullDescription, price, duration, rating, reviews, images, category, includes, notIncludes, itinerary) VALUES (?, ?, ?, ?, ?, 5.0, 0, ?, ?, ?, '[]', ?)`);

tours.forEach(tour => {
  stmt.run(tour.title, tour.shortDescription, tour.fullDescription, tour.price, tour.duration, tour.images, tour.category, tour.includes, tour.itinerary);
});
stmt.finalize((err) => {
  if(err) console.error(err);
  else console.log('Successfully inserted all tours!');
  db.close();
});
